name: Java build and test

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        default: '8'
        type: string
      gradle_version:
        required: false
        default: '7.4.1'
        type: string
jobs:
  build-n-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: ${{ inputs.gradle_version }}

    - name: Execute Gradle build action
      run: ./gradlew build

