name: Java build and test

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        default: '8'
        type: string
      gradle_version:
        required: false
        default: '7.4.1'
        type: string
    secrets:
      gpr_actor:
        required: true
      gpr_token:
        required: true

jobs:

  build-n-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.java_version }}
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      env:
        TESTS_TO_SKIP: REGISTRY, DB
        GITHUB_MDSC_USERNAME: ${{ secrets.gpr_actor }}
        GITHUB_MDSC_TOKEN: ${{ secrets.gpr_token }}
      with:
        gradle-version: ${{ inputs.gradle_version }}
        arguments: build
