name: Java build and test

on:
  workflow_call:
    inputs:
      java_version:
        required: false
        default: '17'
        type: string
      gradle_version:
        required: false
        default: '8.1.1'
        type: string
    secrets:
      gpr_actor:
        required: true
      gpr_token:
        required: true

jobs:

  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java_version }}
          distribution: 'corretto'

      - name: Create distribution directory
        run: mkdir ./distribution

      - name: Create keys directory
        run: mkdir ./distribution/keys

      - name: Create logs directory
        run: mkdir ./logs

      - name: Build
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_MDSC_USERNAME: ${{ secrets.gpr_actor }}
          GITHUB_MDSC_TOKEN: ${{ secrets.gpr_token }}
        with:
          gradle-version: ${{ inputs.gradle_version }}
          arguments: build -x test

      - name: Test
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_MDSC_USERNAME: ${{ secrets.gpr_actor }}
          GITHUB_MDSC_TOKEN: ${{ secrets.gpr_token }}
        with:
          gradle-version: ${{ inputs.gradle_version }}
          arguments: test

      - name: Publish
        uses: ./gradlew publish
        env:
          GITHUB_MDSC_USERNAME: ${{ secrets.gpr_actor }}
          GITHUB_MDSC_TOKEN: ${{ secrets.gpr_token }}
          cache-read-only: false

      - name: Upload logs as artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./logs
